# Generated by Django 5.2.5 on 2025-09-12 17:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('lab_type', models.CharField(choices=[('a01', 'A01: Broken Access Control'), ('a02', 'A02: Cryptographic Failures'), ('a03', 'A03: Injection'), ('a04', 'A04: Insecure Design'), ('a05', 'A05: Security Misconfiguration'), ('a06', 'A06: Vulnerable Components'), ('a07', 'A07: Auth & Identification Failures'), ('a08', 'A08: Software & Data Integrity Failures'), ('a09', 'A09: Security Logging & Monitoring Failures'), ('a10', 'A10: Server-Side Request Forgery')], max_length=20)),
                ('docker_image', models.CharField(help_text='Docker image name for this lab', max_length=255)),
                ('port_mapping', models.CharField(help_text="Port mapping for the container (e.g., '8080:80')", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(blank=True, max_length=100, null=True)),
                ('instance_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('running', 'Running'), ('stopped', 'Stopped'), ('error', 'Error')], default='creating', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('access_url', models.URLField(blank=True, help_text='URL to access the lab instance', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_instances', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='labs_web.labtemplate')),
            ],
        ),
    ]
